project_name: go-fetch

before:
  hooks:
    - go mod tidy

# .goreleaser.yml
builds:
  # 你能用 多个 构建 定义，yaml格式
  - binary: go-fetch
    #  main.go 文件或者主包的路径 .
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{ .Os }}_
      {{ .Arch }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
